#!/bin/bash
echo Git Repository Updater Script for osu!lazer created by UserContributer on Github
echo AKA MasicoreLord from osu!
echo My osu! profile: https://osu.ppy.sh/users/10105376
echo 
git pull
git submodule update --recursive
nuget update -self
nuget restore
echo 
echo Commands Ran:
echo git pull
echo git submodule update --recursive
echo nuget update -self
echo nuget restore
echo 
echo NOTE: Make sure to rebuild if there are any updates.
